### PR TITLE
Add a tag 0.0.4 and update setup.py to use that

### PR DESCRIPTION
**Pull request by jibsheet**
The version wasn't previously bumped for 0.0.2

### CODE REVIEW

**Comment by jibsheet** [comment]
@benpatterson @edx/devops

**Comment by benpatterson** [comment]
Have you happened to check what would happen if we tried to install a github hash with that tag? (i.e., will it uninstall v 0.1)?

**Comment by jibsheet** [comment]
@benpatterson In our jenkins env, we do pip --exists-action w so it rips out the old one and reinstalls.
I need/want to test on paver / AMI builds before merging, going to try and accomplish that before the cutoff tomorrow for the release.

I suspect we can also look at the jenkins worker logs on my build from platform?

**Comment by benpatterson** [comment]
Unfo you couldn't look at the logs on platform because the pip install is quiet; however, if you have devstack running you can just run the github.txt file and see if it uninstalls the other version...

**Comment by jibsheet** [comment]
@benpatterson I worked out my problems.  I accidentally tagged 0.0.3 onto the tip of master, which meant it wasn't checking out my bumped version in setup.py.

I tagged my branch as 0.0.4 and updated setup.py and platform accordingly and things are working better.

**Comment by benpatterson** [comment]
👍

**Pull request merged**
