### PR TITLE
Revert "v1.5.7"

### PR DESCRIPTION
**Pull request by arizzitano**
Reverts edx/pa11ycrawler#58

### CODE REVIEW

**Comment by benpatterson** [comment]
oh noes...any particular reason?

**Comment by arizzitano** [comment]
@benpatterson just realized I forgot to include the `commands` module in setup.py, but fortunately realized this before pushing the package to pypi 😬

**Comment by benpatterson** [comment]
Ah, right. :\

**Comment by mdinino** [comment]
@benpatterson I am still getting EDX github notifications. It doesn't appear that there is a EDX organizztion that I can remove myself from in github. Also, every time I see a notification, I am ignoring it but I think I am on a list to automatically add me to new ones. Is there any way to take me out of the system?

It doesn't matter if it's you or someone else, I just wanted to let you know because I know you.

Also, Hi!

**Comment by arizzitano** [comment]
Abandoning this PR in favor of an intact 1.5.8 :)

**Comment by benpatterson** [comment]
Hi @mdinino I checked and there's nothing I can really do for you; however, my guess is you've just got old cruft that was automatically set to watch while you were still here. You should try going to https://github.com/watching and unfollowing everything edX and see if that clears up the noise for you...

**Pull request closed without merging**
